# This is a TOML document.

title = "Simulation configuration"

[mode]
quiet = true

[paths]
outpath = "./sim_moj/"

[source_types]
jets = true
num_jet_components = [3, 6]
pointlike_gaussians = false
num_pointlike_gaussians = [2, 5]

[flux_scaling]
use_scaling = true
type = "mojave"

[image_options]
bundles_train = 1
bundles_valid = 0
bundles_test = 0
bundle_size = 10
img_size = 128
noise = false
noise_level = 5
